### ISSUE TITLE
Causes false positives.

### ISSUE THREAD

**Issue by Pixelguymm** [nikolaischunk/stop-discord-phishing#2]
The list includes domains that are contained within other, legitimate domains. For example, any `cdn.discordapp.com` URL gets flagged, since `discordapp.co` is on the list. 
I suggest finding the exact domain for every URL in the message, and then checking whether or not or not any of those domains are in on the list, rather than simply checking if the message includes any of the listed domains.

**Comment by nikolaischunk** [comment]
I'm aware of this issue, didn't noticed that I re added the `discordapp.co` Domain, thank you for letting me know. It's a bit difficult to check the exact Domain, I currently don't know a solution for this problem.

**Comment by nikolaischunk** [comment]
Removed `discordapp.co` from the Domain List should not get flagged anymore (give it 5-10minutes to work)
