### ISSUE TITLE
discord.gift is flagged as malicious [false positive]

### ISSUE THREAD

**Issue by adri326** [nikolaischunk/stop-discord-phishing#3]
This is likely due to the domain `iscord.gift` present in the database, which is defined at line 2802 as of writing this:

https://github.com/nikolaischunk/discord-phishing-links/blob/main/domain-list.json#L2802

**Comment by nikolaischunk** [comment]
Oh, thanks another false positive flag, I currently don't know how to better catch included domains in a string then the current implementation, if you do know a better way feel free to create a PR, I would appreciate it.

**Comment by nikolaischunk** [comment]
Removed `iscord.gift` from the domain List
